sudo: false
dist: bionic
language: csharp
mono: none
dotnet: 2.0.0
solution: Com.Danliris.Service.Sales.sln
env:
    - ASPNETCORE_ENVIRONMENT=Test

install: true

before_script:
    - sudo apt-get install libgdiplus

script:
    - dotnet restore Com.Danliris.Sales.Test/Com.Danliris.Sales.Test.csproj
    - dotnet build Com.Danliris.Sales.Test/Com.Danliris.Sales.Test.csproj
    - dotnet test Com.Danliris.Sales.Test/Com.Danliris.Sales.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

after_success:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - ./codecov -f "/home/travis/build/danliris/com-danliris-service-sales/Com.Danliris.Sales.Test/coverage.info"
